/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryImportRouteImport } from './routes/library-import'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountRequestsRouteImport } from './routes/admin.account-requests'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminBusinessTypesRouteImport } from './routes/admin.business-types'
import { Route as AdminKpisRouteImport } from './routes/admin.kpis'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPasswordResetsRouteImport } from './routes/admin.password-resets'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantCreditRouteImport } from './routes/merchant.credit'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantPosRouteImport } from './routes/merchant.pos'
import { Route as MerchantProductsRouteImport } from './routes/merchant.products'
import { Route as MerchantReportsRouteImport } from './routes/merchant.reports'
import { Route as MerchantReturnsRouteImport } from './routes/merchant.returns'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterCustomerRouteImport } from './routes/register.customer'
import { Route as RegisterMerchantRouteImport } from './routes/register.merchant'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as AdminUserFileUserIdRouteImport } from './routes/admin.user-file.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryImportRoute = LibraryImportRouteImport.update({
  id: '/library-import',
  path: '/library-import',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRequestsRoute = AdminAccountRequestsRouteImport.update({
  id: '/account-requests',
  path: '/account-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessTypesRoute = AdminBusinessTypesRouteImport.update({
  id: '/business-types',
  path: '/business-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisRoute = AdminKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasswordResetsRoute = AdminPasswordResetsRouteImport.update({
  id: '/password-resets',
  path: '/password-resets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCreditRoute = MerchantCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantPosRoute = MerchantPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProductsRoute = MerchantProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReportsRoute = MerchantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReturnsRoute = MerchantReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCustomerRoute = RegisterCustomerRouteImport.update({
  id: '/register/customer',
  path: '/register/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMerchantRoute = RegisterMerchantRouteImport.update({
  id: '/register/merchant',
  path: '/register/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserFileUserIdRoute = AdminUserFileUserIdRouteImport.update({
  id: '/user-file/$userId',
  path: '/user-file/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/business-types': typeof AdminBusinessTypesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/merchant': typeof RegisterMerchantRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/user-file/$userId': typeof AdminUserFileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/business-types': typeof AdminBusinessTypesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/merchant': typeof RegisterMerchantRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/user-file/$userId': typeof AdminUserFileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/change-password': typeof ChangePasswordRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/business-types': typeof AdminBusinessTypesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/merchant': typeof RegisterMerchantRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/user-file/$userId': typeof AdminUserFileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/change-password'
    | '/credit'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/account-requests'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/business-types'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/password-resets'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/register/customer'
    | '/register/merchant'
    | '/store/$storeId'
    | '/admin/'
    | '/merchant/'
    | '/register/'
    | '/admin/user-file/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/change-password'
    | '/credit'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/account-requests'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/business-types'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/password-resets'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/register/customer'
    | '/register/merchant'
    | '/store/$storeId'
    | '/admin'
    | '/merchant'
    | '/register'
    | '/admin/user-file/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/change-password'
    | '/credit'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/account-requests'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/business-types'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/password-resets'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/register/customer'
    | '/register/merchant'
    | '/store/$storeId'
    | '/admin/'
    | '/merchant/'
    | '/register/'
    | '/admin/user-file/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CreditRoute: typeof CreditRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LibraryImportRoute: typeof LibraryImportRoute
  LocationsRoute: typeof LocationsRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  WalletRoute: typeof WalletRoute
  RegisterCustomerRoute: typeof RegisterCustomerRoute
  RegisterMerchantRoute: typeof RegisterMerchantRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-import': {
      id: '/library-import'
      path: '/library-import'
      fullPath: '/library-import'
      preLoaderRoute: typeof LibraryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account-requests': {
      id: '/admin/account-requests'
      path: '/account-requests'
      fullPath: '/admin/account-requests'
      preLoaderRoute: typeof AdminAccountRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business-types': {
      id: '/admin/business-types'
      path: '/business-types'
      fullPath: '/admin/business-types'
      preLoaderRoute: typeof AdminBusinessTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis': {
      id: '/admin/kpis'
      path: '/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AdminKpisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/password-resets': {
      id: '/admin/password-resets'
      path: '/password-resets'
      fullPath: '/admin/password-resets'
      preLoaderRoute: typeof AdminPasswordResetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/credit': {
      id: '/merchant/credit'
      path: '/credit'
      fullPath: '/merchant/credit'
      preLoaderRoute: typeof MerchantCreditRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/pos': {
      id: '/merchant/pos'
      path: '/pos'
      fullPath: '/merchant/pos'
      preLoaderRoute: typeof MerchantPosRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/products': {
      id: '/merchant/products'
      path: '/products'
      fullPath: '/merchant/products'
      preLoaderRoute: typeof MerchantProductsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/reports': {
      id: '/merchant/reports'
      path: '/reports'
      fullPath: '/merchant/reports'
      preLoaderRoute: typeof MerchantReportsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/returns': {
      id: '/merchant/returns'
      path: '/returns'
      fullPath: '/merchant/returns'
      preLoaderRoute: typeof MerchantReturnsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/customer': {
      id: '/register/customer'
      path: '/register/customer'
      fullPath: '/register/customer'
      preLoaderRoute: typeof RegisterCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/merchant': {
      id: '/register/merchant'
      path: '/register/merchant'
      fullPath: '/register/merchant'
      preLoaderRoute: typeof RegisterMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user-file/$userId': {
      id: '/admin/user-file/$userId'
      path: '/user-file/$userId'
      fullPath: '/admin/user-file/$userId'
      preLoaderRoute: typeof AdminUserFileUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRequestsRoute: typeof AdminAccountRequestsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminBusinessTypesRoute: typeof AdminBusinessTypesRoute
  AdminKpisRoute: typeof AdminKpisRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPasswordResetsRoute: typeof AdminPasswordResetsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserFileUserIdRoute: typeof AdminUserFileUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRequestsRoute: AdminAccountRequestsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminBusinessTypesRoute: AdminBusinessTypesRoute,
  AdminKpisRoute: AdminKpisRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPasswordResetsRoute: AdminPasswordResetsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserFileUserIdRoute: AdminUserFileUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantCreditRoute: typeof MerchantCreditRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantPosRoute: typeof MerchantPosRoute
  MerchantProductsRoute: typeof MerchantProductsRoute
  MerchantReportsRoute: typeof MerchantReportsRoute
  MerchantReturnsRoute: typeof MerchantReturnsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantCreditRoute: MerchantCreditRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantPosRoute: MerchantPosRoute,
  MerchantProductsRoute: MerchantProductsRoute,
  MerchantReportsRoute: MerchantReportsRoute,
  MerchantReturnsRoute: MerchantReturnsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CreditRoute: CreditRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LibraryImportRoute: LibraryImportRoute,
  LocationsRoute: LocationsRoute,
  MerchantRoute: MerchantRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  WalletRoute: WalletRoute,
  RegisterCustomerRoute: RegisterCustomerRoute,
  RegisterMerchantRoute: RegisterMerchantRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
